name: media-stack
services:
  # To use/enable VPN, Run this compose file with --profile=vpn. Its highly recommended to use VPN.
  vpn:
    ## Read https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers for details on configuring VPN for your service provider.
    profiles: ["vpn"]
    container_name: vpn
    image: qmcgaw/gluetun:latest 
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}

      ## For list of server countries, visit https://raw.githubusercontent.com/qdm12/gluetun/master/internal/storage/servers.json
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - VPN_TYPE=openvpn # or wireguard. 
      - OPENVPN_PROTOCOL=udp
      - DOT=on
      - FIREWALL=on

    networks:
      - mynetwork

    devices:
      - /dev/net/tun:/dev/net/tun
      
    # Uncomment/enable below ports if VPN is used/enabled
    ports:
      # qbittorrent ports
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
      # prowlarr ports
      - 9696:9696
    volumes:
      - ${DATA_DIR}/config/gluetun:/gluetun
    restart: "unless-stopped"

    # Healthcheck disabled via DISABLE_HEALTHCHECK=true env var
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z 127.0.0.1 9999"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  ## Default credentials of qBittorrent - Username: admin password: adminadmin ##
  ## Change password after install from UI --> Tools --> Options --> WebUI ##
  qbittorrent:
    profiles: ["vpn", "no-vpn"]
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:5.2.0

    # Uncomment below if vpn is enabled
    depends_on:               # Uncomment this line if vpn is enabled
      vpn:                    # Uncomment this line if vpn is enabled
        condition: service_healthy # Uncomment this line if vpn is enabled

    # Uncomment below line if vpn is enabled
    network_mode: service:vpn

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=5080
    volumes:
      - ${DATA_DIR}/config/qbittorrent:/config
      - ${DATA_DIR}:/data

    restart: "unless-stopped"

  radarr:
    profiles: ["vpn", "no-vpn"]
    container_name: radarr
    image: lscr.io/linuxserver/radarr:6.1.1
    networks:
      mynetwork:
        ipv4_address: ${RADARR_STATIC_CONTAINER_IP} # It should be available IPv4 address in range of docker network `mynetwork` e.g. 172.20.0.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - ${DATA_DIR}/config/radarr:/config
      - ${DATA_DIR}:/data
    restart: "unless-stopped"

  sonarr:
    profiles: ["vpn", "no-vpn"]
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      mynetwork:
        ipv4_address: ${SONARR_STATIC_CONTAINER_IP} # It should be available IPv4 address in range of docker network `mynetwork` e.g. 172.20.0.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ${DATA_DIR}/config/sonarr:/config
      - ${DATA_DIR}:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    profiles: ["vpn", "no-vpn"]
    container_name: prowlarr
    image: linuxserver/prowlarr:2.3.5

    # Uncomment below if vpn is enabled
    depends_on:               # Uncomment this line if vpn is enabled
      vpn:                    # Uncomment this line if vpn is enabled
        condition: service_healthy # Uncomment this line if vpn is enabled
    network_mode: service:vpn # Uncomment this line if vpn is enabled

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ${DATA_DIR}/config/prowlarr:/config

    restart: unless-stopped

  recommendarr:
    profiles: ["recommendarr"]
    container_name: recommendarr
    image: tannermiddleton/recommendarr:v1.4.4
    networks:
      - mynetwork
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - PORT=3000
      - PUBLIC_URL=https://localhost:3000 # Change this public URL if you are accessing recommendarr on a domain
    volumes:
      - ${DATA_DIR}/config/recommendarr:/app/server/data
    ports:
      - 3000:3000
    restart: unless-stopped

  seerr:
    profiles: ["vpn", "no-vpn"]
    image: ghcr.io/seerr-team/seerr:v3.2.0
    container_name: seerr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - PORT=5055
    volumes:
      - ${DATA_DIR}/config/seerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  jellyfin:
    profiles: ["vpn", "no-vpn"]
    image: linuxserver/jellyfin:10.11.9
    container_name: jellyfin
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      #- JELLYFIN_PublishedServerUrl=
    volumes:
      - ${DATA_DIR}/config/jellyfin:/config
      - ${DATA_DIR}:/data
  # devices:
   #  - /dev/videoN:/dev/videoN # Mount GPU device 
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped

  flaresolverr:
    profiles: ["vpn"]
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    network_mode: service:vpn
    environment:
      - LOG_LEVEL=info
      - TZ=UTC
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80                            # Opens standard local HTTP traffic
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mounts your local config as read-only (./nginx.conf in the media-stack dir is the local file here)
    networks:
      - mynetwork  


networks:
  mynetwork:
    external: true
